### ISSUE TITLE
Add filter for show/hide (My Availability).

### ISSUE THREAD

**Issue by slhernandez** [glg/go-engage#7]
Need to figure out how to let users to show and hide their own availability.  This can clutter the calendar workspace when viewing (All Council Members).

**Comment by slhernandez** [comment]
I added some markup and styles for exposing a checkbox for show/hide "My Availability".  Need backend hookup.

**Comment by stovenator** [comment]
Fixed with 3fccb5897e973c2794670ef61c29529b2319801b
